# Generated by Django 5.1.5 on 2025-01-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='pic',
            field=models.FileField(default='media/admin.png', upload_to='media/images/'),
        ),
        migrations.CreateModel(
            name='learners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('pic', models.FileField(default='media/boy.png', upload_to='media/images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
