# Generated by Django 5.1.5 on 2025-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.FileField(default='media/course_pic.png', upload_to='media/images'),
        ),
    ]
