# Generated by Django 5.1.5 on 2025-02-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_course_course_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=60)),
                ('company_discription', models.TextField()),
                ('company_email', models.EmailField(max_length=30, unique=True)),
                ('company_pic', models.FileField(default='media/', upload_to='media/images')),
                ('contact_no', models.CharField(max_length=15)),
                ('company_website', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
