# Generated by Django 5.1.5 on 2025-02-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_pic',
            field=models.FileField(default='media/tata.png', upload_to='media/images'),
        ),
        migrations.CreateModel(
            name='enrollcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('fees_status', models.CharField(max_length=20)),
                ('paid_fees', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.learners')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
