# Generated by Django 5.1.5 on 2025-02-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_company_company_pic_enrollcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=456),
        ),
    ]
