# Generated by Django 5.1.5 on 2025-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
